name: reviewdog
on: [pull_request]
permissions: write-all
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@v1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          android: true
          fail_on_error: true
